### PR TITLE
stderr UserWarning removed from xcue.ipynb

### PR DESCRIPTION
**Pull request by konstntokas**
I removed the stderr UserWarning from xcue.ipynb.
FYI: @sonicious

### CODE REVIEW

**Comment by konstntokas** [comment]
@davemlz can you help me with the broken pipeline? 
There is something wrong with the Earth Engine account in the package `ee`

```
ee.ee_exception.EEException: Please authorize access to your Earth Engine account by running

earthengine authenticate
```

**Comment by davemlz** [comment]
Hi @konstntokas,

Where is this error happening? I just tested everything, or are you talking about the test builds in GH?

**Comment by konstntokas** [comment]
> Hi @konstntokas,
> 
> Where is this error happening? I just tested everything, or are you talking about the test builds in GH?

It is happening in the test/builds. The error message 

```
E   ee.ee_exception.EEException: Please authorize access to your Earth Engine account by running
E   
E   earthengine authenticate
E   
E   in your command line, or ee.Authenticate() in Python, and then retry.
```
is given in the [output](https://github.com/awesome-spectral-indices/spyndex/actions/runs/9298836619/job/25591490613?pr=27) of the workflows.

**Comment by davemlz** [comment]
Ah ok. That's fine. I need to fix it, but not in top list for now.

**Comment by konstntokas** [comment]
> Ah ok. That's fine. I need to fix it, but not in top list for now.

Ok thanks for your quick replies :)

**Pull request merged**
